/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financial.calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author CriCr
 */
public class Finacial_calculator extends javax.swing.JFrame {

    /**
     * Creates new form Finacial_calculator
     */
    public Finacial_calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCustomerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbInvestmentType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rb5years = new javax.swing.JRadioButton();
        rb10Years = new javax.swing.JRadioButton();
        rb15Years = new javax.swing.JRadioButton();
        NaviBar = new javax.swing.JMenuBar();
        NavbarFile = new javax.swing.JMenu();
        nbBtnExit = new javax.swing.JMenuItem();
        NavbarEdit = new javax.swing.JMenu();
        NBbtnCalculate = new javax.swing.JMenuItem();
        NavbarBtnClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer Name:");

        jLabel2.setText("Enter Amount:");

        jLabel3.setText("Select Type:");

        cbInvestmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moderate", "Aggressive" }));

        jLabel4.setText("Select Term:");

        rb5years.setText("5 Years");
        rb5years.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5yearsActionPerformed(evt);
            }
        });

        rb10Years.setText("10 Years");
        rb10Years.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb10YearsActionPerformed(evt);
            }
        });

        rb15Years.setText("15 Years");
        rb15Years.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb15YearsActionPerformed(evt);
            }
        });

        NavbarFile.setText("File");

        nbBtnExit.setText("Exit");
        nbBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbBtnExitActionPerformed(evt);
            }
        });
        NavbarFile.add(nbBtnExit);

        NaviBar.add(NavbarFile);

        NavbarEdit.setText("Edit");

        NBbtnCalculate.setText("Calculate");
        NBbtnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NBbtnCalculateActionPerformed(evt);
            }
        });
        NavbarEdit.add(NBbtnCalculate);

        NavbarBtnClear.setText("Clear");
        NavbarBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavbarBtnClearActionPerformed(evt);
            }
        });
        NavbarEdit.add(NavbarBtnClear);

        NaviBar.add(NavbarEdit);

        setJMenuBar(NaviBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb5years)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addComponent(cbInvestmentType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rb10Years)
                            .addComponent(rb15Years))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbInvestmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb5years))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb10Years)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb15Years)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void NBbtnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NBbtnCalculateActionPerformed
        try{
            FinancialCalculator();//throws exception so we catch the exception
        }
        catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex, "ErrorMessage"
                        , JOptionPane.ERROR_MESSAGE); // and send error message
        }
    }//GEN-LAST:event_NBbtnCalculateActionPerformed

    private void NavbarBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavbarBtnClearActionPerformed
       //clear all fields and reset to defualt 
       TxtCustomerName.setText(""); 
       TxtAmount.setText("");
       rb5years.setSelected(false);
       rb10Years.setSelected(false);
       rb15Years.setSelected(false);
       cbInvestmentType.setSelectedIndex(0);
    }//GEN-LAST:event_NavbarBtnClearActionPerformed

    private void nbBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbBtnExitActionPerformed
        System.exit(0); // close the program
    }//GEN-LAST:event_nbBtnExitActionPerformed

    private void rb5yearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5yearsActionPerformed
        if(rb10Years.isSelected()){ //make sure the other radiobuttons 
            rb10Years.setSelected(false);//are not selected
        }
        if(rb15Years.isSelected()){
            rb15Years.setSelected(false);
        }
    }//GEN-LAST:event_rb5yearsActionPerformed

    private void rb10YearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb10YearsActionPerformed
        if(rb5years.isSelected()){//make sure the other radiobuttons
            rb5years.setSelected(false);//are not selected
        }
        if(rb15Years.isSelected()){
            rb15Years.setSelected(false);
        }
    }//GEN-LAST:event_rb10YearsActionPerformed

    private void rb15YearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb15YearsActionPerformed
         if(rb10Years.isSelected()){//make sure the other radiobuttons
            rb10Years.setSelected(false);//are not selected
        }
        if(rb5years.isSelected()){
            rb5years.setSelected(false);
        }
    }//GEN-LAST:event_rb15YearsActionPerformed

    /**
     * this method makes a financial calculation
     * @throws Exception math brings many exceptions
     */
    private void FinancialCalculator() throws Exception{
        double finalAmount = 0;
        double intialBalance = 0;
        double InterrestRate = 0;
        int years = 0;
        if(rb5years.isSelected()){
            years = 5;
        }
        else if(rb10Years.isSelected()){
             years = 10;
        }
        else if(rb15Years.isSelected()){
            years = 15;
        }
        else{
            throw new Exception("No Year Value Selected! _code line 227: "
                    + "method FinancialCalculator");
        }
        intialBalance = Double.parseDouble(TxtAmount.getText());
        if(cbInvestmentType.getSelectedIndex() == 0){
            InterrestRate = 0.15;
        }
        if(cbInvestmentType.getSelectedIndex() == 1){
            InterrestRate = 0.10;
        }
        finalAmount = intialBalance*(Math.pow((1+InterrestRate), years));
        PrintToScreen(finalAmount, years);
    }
    
    /**
     * this is FinancialCalculator helper method
     * @param finalAmount this is the result from FinancialCalculator
     * @param Years this is the choice the year selected
     */
    private void PrintToScreen(double finalAmount, int Years){
        String message = "Investment Report" + "\n"+"\n" + "Customer Name: " 
                +TxtCustomerName.getText() + "\n" +"Original Amount: R " 
                +TxtAmount.getText()+ "\n" +"Years invested: " 
                 +Years+ "\n" + "Final Amount: R " 
                + String.format("%.2f", finalAmount);
        JOptionPane.showMessageDialog(null, message);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finacial_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finacial_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finacial_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finacial_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finacial_calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem NBbtnCalculate;
    private javax.swing.JMenuItem NavbarBtnClear;
    private javax.swing.JMenu NavbarEdit;
    private javax.swing.JMenu NavbarFile;
    private javax.swing.JMenuBar NaviBar;
    private javax.swing.JTextField TxtAmount;
    private javax.swing.JTextField TxtCustomerName;
    private javax.swing.JComboBox<String> cbInvestmentType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem nbBtnExit;
    private javax.swing.JRadioButton rb10Years;
    private javax.swing.JRadioButton rb15Years;
    private javax.swing.JRadioButton rb5years;
    // End of variables declaration//GEN-END:variables
}
